### ISSUE TITLE
Release a new version to Crates.io to use oboe with ndk 0.8

### ISSUE THREAD

**Issue by ameknite** [katyo/oboe-rs#59]
# Objective:
Use oboe with ndk 0.8

In #57 ndk was updated to 0.8. but a new version to Crates.io has not being released.

alternatives:

```toml
[dependencies]
oboe = { git = "https://github.com/katyo/oboe-rs", branch = "master", features=["ndk"]}
```
